# Generated by Django 3.0.6 on 2020-05-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Rating',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
