# Generated by Django 3.0.6 on 2020-05-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200510_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='subcategory',
            new_name='address',
        ),
    ]
